apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  {{ template "iter8-autox.labels" . }}
stringData:
  config.yaml: |
    specs:
    {{- range $releaseGroupSpecName, $releaseGroupSpec := .Values.releaseGroupSpecs }}
      {{ $releaseGroupSpecName }}:
        trigger:
          group: {{ $releaseGroupSpec.trigger.group }}
          version: {{ $releaseGroupSpec.trigger.version }}
          resource: {{ $releaseGroupSpec.trigger.resource }}
          name: {{ $releaseGroupSpec.trigger.name }}
          namespace: {{ $releaseGroupSpec.trigger.namespace }}
        releaseSpecs:
        {{- range $releaseSpecName, $releaseSpec := $releaseGroupSpec.releaseSpecs }}
          {{ $releaseSpecName }}:
            repoURL: {{ $releaseSpec.repoURL }}
            name: {{ $releaseSpec.name }}
            values: {{ $releaseSpec.values }}
            version: {{ $releaseSpec.version }}
        {{- end }}
    {{- end }}
{{- range $releaseGroupSpecName, $releaseGroupSpec := .Values.releaseGroupSpecs }}
{{ $hash := print $releaseGroupSpec | sha256sum | trunc 5 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: autox-{{ $releaseGroupSpecName }}-{{ $hash }}
  labels:
    iter8.tools/autox-group: {{ $releaseGroupSpecName }}
{{- end }}