name: integration tests for iter8lib

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  integration-load-test-http:
    name: local httpbin tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checkout repository
      uses: actions/checkout@v2


    - uses: azure/setup-helm@v1
      with:
        version: '3.8.0'
    
    - name: Install Iter8
      run: |
        wget https://github.com/iter8-tools/iter8/releases/download/v0.9.0/iter8-linux-amd64.tar.gz
        tar -xvf iter8-linux-amd64.tar.gz
        mv linux-amd64/iter8 /usr/local/bin

    - name: run httpbin
      run: |
        set -e
        docker pull kennethreitz/httpbin
        docker run -p 80:80 kennethreitz/httpbin &
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1/get)" != "200" ]]; do
          sleep 5; 
        done;

    - name: load test GET endpoint
      run: |
        set -e
        cd testlibchart/load-test-http
        helm dependency update .
        iter8 gen -c . --set url=http://127.0.0.1/get
        cat experiment.yaml
        iter8 run
        iter8 assert -c completed -c nofailure -c slos

    - name: load test GET endpoint
      run: |
        set -e
        cd testlibchart/load-test-http
        helm dependency update .
        iter8 gen -c . --set url=http://127.0.0.1/get \
                  --set SLOs.http/latency-p25=80 \
                  --set SLOs.http/latency-p50=100 \
                  --set SLOs.http/latency-'p95\.0'=200
        cat experiment.yaml
        iter8 run
        iter8 assert -c completed -c nofailure -c slos

    - name: load test POST endpoint (image/jpeg)
      run: |
        set -e
        cd testlibchart/load-test-http
        helm dependency update .
        iter8 gen -c . --set url=http://127.0.0.1/post \
                  --set payloadURL=https://cdn.pixabay.com/photo/2021/09/08/17/58/poppy-6607526_1280.jpg \
                  --set contentType="image/jpeg" \
                  --set SLOs.http/latency-p25=80 \
                  --set SLOs.http/latency-p50=100 \
                  --set SLOs.http/latency-'p95\.0'=200
        cat experiment.yaml
        iter8 run
        iter8 assert -c completed -c nofailure -c slos

  integration-load-test-grpc:
    name: local grpc tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Iter8
      run: |
        wget https://github.com/iter8-tools/iter8/releases/download/v0.9.0/iter8-linux-amd64.tar.gz
        tar -xvf iter8-linux-amd64.tar.gz
        mv linux-amd64/iter8 /usr/local/bin

    - name: run greeter
      run: |
        git clone -b v1.43.0 https://github.com/grpc/grpc-go
        cd grpc-go/examples/helloworld
        go build greeter_server/main.go
        ./main &

    - name: load test grpc service method
      run: |
        set -e
        cd testlibchart/load-test-grpc
        helm dependency update .
        export LOG_LEVEL=trace
        iter8 gen -c . --set host="127.0.0.1:50051" \
                  --set call="helloworld.Greeter.SayHello" \
                  --set protoURL="https://raw.githubusercontent.com/grpc/grpc-go/master/examples/helloworld/helloworld/helloworld.proto" \
                  --set data.name="frodo" \
                  --set SLOs.grpc/error-rate=0 \
                  --set SLOs.grpc/latency/mean=50 \
                  --set SLOs.grpc/latency/p90=100 \
                  --set SLOs.grpc/latency/p'97\.5'=200
        echo "experiment ... "
        cat experiment.yaml
        iter8 run
        echo "report ..."
        iter8 report
        echo "assert... "
        iter8 assert -c completed -c nofailure -c slos
